name: Raspberry Pi 5

on:
    workflow_dispatch:
        inputs:
            host_name:
                description: "Hostname"
                default: neurobionics
                required: true
            user:
                description: "Username"
                required: true
                default: pi
            password:
                description: "Password"
                required: true
                default: neurobionics
            wifi_cc:
                description: "WiFi Country Code"
                required: true
                default: "US"
                type: choice
                options:
                    - US
                    - GB
                    - DE
                    - FR
                    - IT
                    - ES
                    - CA
                    - AU
                    - JP
                    - CN
                    - KR
                    - TW
                    - SG
                    - IN
                    - BR
                    - RU
                    - ZA
                    - SA
                    - AE
                    - EG
                    - IL
                    - TR
                    - ID
                    - TH
                    - VN
                    - PH
                    - MY
                    - MX
                    - AR
                    - CL
                    - CO
                    - PE
                    - UY
                    - EC
                    - BO
                    - PY
                    - CR
                    - PA
                    - GT
                    - HN
                    - SV
                    - NI
                    - DO
                    - JM
                    - HT
                    - CU
                    - VE
            wifi_ssid:
                description: "Additional Network SSID"
                required: false
            wifi_password:
                description: "Additional Network Password"
                required: false
            wpa_ssid:
                description: "Access Point SSID"
                required: true
                default: NeurobionicsRPi
            wpa_password:
                description: "Access Point Password"
                required: true
                default: neurobionics
env:
    PIFILE: rpi5

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Check secrets
              run: |
                  if [[ -z "${{ secrets.MWIRELESS_PASSWORD }}" || -z "${{ secrets.EMAIL_ADDRESS }}" || -z "${{ secrets.MWIRELESS_IDENTITY }}" ]]; then
                      echo "MWIRELESS_PASSWORD, EMAIL_ADDRESS, or MWIRELESS_IDENTITY secrets are empty"
                      exit 1
                  fi
            - uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Write env variables
              run: |
                  echo HOSTNAME="${{ github.event.inputs.host_name }}" >> $GITHUB_ENV
                  echo USER="${{ github.event.inputs.user }}" >> $GITHUB_ENV
                  echo USERPASSWORD="${{ github.event.inputs.password }}" >> $GITHUB_ENV
                  echo MWIRELESS_IDENTITY="${{ secrets.MWIRELESS_IDENTITY }}" >> $GITHUB_ENV
                  echo MWIRELESS_PASSWORD="${{ secrets.MWIRELESS_PASSWORD }}" >> $GITHUB_ENV
                  echo WIFI_CC="${{ github.event.inputs.wifi_cc }}" >> $GITHUB_ENV
                  echo WIFI_SSID="${{ github.event.inputs.wifi_ssid }}" >> $GITHUB_ENV
                  echo WIFI_PASSWORD="${{ github.event.inputs.wifi_password }}" >> $GITHUB_ENV
                  echo AP_SSID="${{ github.event.inputs.wpa_ssid }}" >> $GITHUB_ENV
                  echo AP_PASSWORD="${{ github.event.inputs.wpa_password }}" >> $GITHUB_ENV
                  echo EMAIL=\"${{ secrets.EMAIL_ADDRESS }}\" >> $GITHUB_ENV
            - name: Build image
              uses: Nature40/pimod@master
              with:
                  pifile: ${PIFILE}.Pifile

            - name: Make tarball
              run: |
                  tar -czvf ${PIFILE}.tar.gz ${PIFILE}.img
            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.workflow }}-${{ github.sha }}.zip
                  path: ${PIFILE}.img
